-- MySQL Script generated by MySQL Workbench
-- 12/31/15 11:06:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tcslavens
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tcslavens
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tcslavens` DEFAULT CHARACTER SET latin1 ;
USE `tcslavens` ;

-- -----------------------------------------------------
-- Table `tcslavens`.`a_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcslavens`.`a_status` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tcslavens`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcslavens`.`address` (
  `contact_id` INT(15) NOT NULL,
  `type` INT(15) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `state` VARCHAR(2) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `zip` INT(10) NOT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tcslavens`.`address_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcslavens`.`address_types` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tcslavens`.`agent_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcslavens`.`agent_status` (
  `contact_id` INT(15) NOT NULL,
  `agent_status` INT(15) NOT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tcslavens`.`contact_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcslavens`.`contact_type` (
  `id` INT(15) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tcslavens`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcslavens`.`contacts` (
  `id` INT(15) NOT NULL AUTO_INCREMENT,
  `tc_id` INT(15) NOT NULL,
  `first_name` VARCHAR(70) NOT NULL,
  `last_name` VARCHAR(30) NOT NULL,
  `company` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `type` VARCHAR(20) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `mail_list` VARCHAR(10) NULL DEFAULT NULL,
  `add_date` VARCHAR(20) NOT NULL,
  `agent_start_date` VARCHAR(20) NOT NULL,
  `bre_license_number` INT(10) NOT NULL,
  `license_expiration` INT(20) NOT NULL,
  `commission_percent` INT(3) NOT NULL,
  `commission_fee` INT(10) NOT NULL,
  `agent_rating` INT(10) NOT NULL,
  `source` VARCHAR(45) NULL,
  `license_status_id` VARCHAR(15) NULL,
  `mail_list` VARCHAR(15) NULL,
  PRIMARY KEY (`id`),
  INDEX `password` (`password` ASC),
  INDEX `tc_id` (`tc_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 470
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tcslavens`.`date_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcslavens`.`date_types` (
  `id` INT(15) NOT NULL AUTO_INCREMENT,
  `date` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tcslavens`.`parties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcslavens`.`parties` (
  `id` INT(15) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `name` (`name` ASC),
  INDEX `id` (`id` ASC),
  INDEX `id_2` (`id` ASC),
  INDEX `id_3` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tcslavens`.`sides`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcslavens`.`sides` (
  `id` INT(15) NOT NULL AUTO_INCREMENT,
  `side` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tcslavens`.`item_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcslavens`.`item_types` (
  `id` TINYINT(1) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tcslavens`.`queues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcslavens`.`queues` (
  `id` INT(15) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tcslavens`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcslavens`.`items` (
  `id` INT(15) NOT NULL AUTO_INCREMENT,
  `heading` VARCHAR(50) NOT NULL,
  `body` VARCHAR(1000) NOT NULL,
  `date_type` INT(15) NOT NULL,
  `days` INT(3) NOT NULL,
  `queue` INT(15) NOT NULL DEFAULT '1',
  `tc_id` INT(15) NOT NULL,
  `item_type` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `date_type` (`date_type` ASC),
  INDEX `default_queue` (`queue` ASC),
  INDEX `tc_id` (`tc_id` ASC),
  INDEX `item_type` (`item_type` ASC),
  INDEX `tc_id_2` (`tc_id` ASC),
  INDEX `queue` (`queue` ASC),
  INDEX `date_type_2` (`date_type` ASC),
  CONSTRAINT `items_ibfk_1`
    FOREIGN KEY (`item_type`)
    REFERENCES `tcslavens`.`item_types` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `items_ibfk_2`
    FOREIGN KEY (`tc_id`)
    REFERENCES `tcslavens`.`contacts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `items_ibfk_3`
    FOREIGN KEY (`queue`)
    REFERENCES `tcslavens`.`queues` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `items_ibfk_4`
    FOREIGN KEY (`date_type`)
    REFERENCES `tcslavens`.`date_types` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 158
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tcslavens`.`item_parties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcslavens`.`item_parties` (
  `id` INT(15) NOT NULL AUTO_INCREMENT,
  `party` INT(15) NOT NULL,
  `side` INT(15) NOT NULL DEFAULT '2',
  `item` INT(15) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `side` (`side` ASC),
  INDEX `role` (`party` ASC),
  INDEX `role_2` (`party` ASC),
  INDEX `role_3` (`party` ASC),
  INDEX `side_2` (`side` ASC),
  INDEX `role_4` (`party` ASC),
  INDEX `side_3` (`side` ASC),
  INDEX `item` (`item` ASC),
  CONSTRAINT `item_parties_ibfk_1`
    FOREIGN KEY (`party`)
    REFERENCES `tcslavens`.`parties` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `item_parties_ibfk_2`
    FOREIGN KEY (`side`)
    REFERENCES `tcslavens`.`sides` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `item_parties_ibfk_3`
    FOREIGN KEY (`item`)
    REFERENCES `tcslavens`.`items` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 261
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tcslavens`.`phone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcslavens`.`phone` (
  `contact_id` INT(11) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `type` INT(15) NOT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tcslavens`.`templates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcslavens`.`templates` (
  `id` INT(15) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `user_id` INT(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tcslavens`.`template_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcslavens`.`template_items` (
  `template` INT(15) NOT NULL,
  `item` INT(15) NOT NULL,
  INDEX `template` (`template` ASC),
  INDEX `item` (`item` ASC),
  CONSTRAINT `template_items_ibfk_1`
    FOREIGN KEY (`template`)
    REFERENCES `tcslavens`.`templates` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `template_items_ibfk_2`
    FOREIGN KEY (`item`)
    REFERENCES `tcslavens`.`items` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tcslavens`.`transaction_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcslavens`.`transaction_status` (
  `id` INT(15) NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tcslavens`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcslavens`.`transactions` (
  `id` INT(15) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `status` INT(15) NOT NULL DEFAULT '1',
  `user_id` INT(15) NOT NULL,
  `city` VARCHAR(30) NOT NULL,
  `state` VARCHAR(2) NOT NULL,
  `zip` VARCHAR(10) NOT NULL,
  `side` INT(15) NULL,
  `escrow_number` VARCHAR(45) NULL,
  `mls_number` VARCHAR(45) NULL,
  `photo_link` VARCHAR(600) NULL,
  `hw_yes_no` VARCHAR(45) NULL,
  `hw_who_pays` VARCHAR(45) NULL,
  `hw_company` VARCHAR(45) NULL,
  `hw_amount` VARCHAR(45) NULL,
  `hw_upgrades` VARCHAR(45) NULL,
  `commission` VARCHAR(45) NULL,
  `apn` VARCHAR(45) NULL,
  `nhd_who_pays` VARCHAR(45) NULL,
  `nhd_company` VARCHAR(45) NULL,
  `year_built` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `user_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `STATUS` (`status` ASC),
  INDEX `STATUS_2` (`status` ASC),
  INDEX `user_id` (`user_id` ASC),
  CONSTRAINT `transactions_ibfk_1`
    FOREIGN KEY (`status`)
    REFERENCES `tcslavens`.`transaction_status` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `transactions_ibfk_2`
    FOREIGN KEY (`status`)
    REFERENCES `tcslavens`.`transaction_status` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `transactions_ibfk_3`
    FOREIGN KEY (`user_id`)
    REFERENCES `tcslavens`.`contacts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 167
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tcslavens`.`transaction_dates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcslavens`.`transaction_dates` (
  `id` INT(15) NOT NULL AUTO_INCREMENT,
  `date` INT(15) NOT NULL,
  `transaction` INT(15) NOT NULL,
  `calendar_date` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `date` (`date` ASC, `transaction` ASC),
  INDEX `transaction` (`transaction` ASC),
  CONSTRAINT `transaction_dates_ibfk_1`
    FOREIGN KEY (`date`)
    REFERENCES `tcslavens`.`date_types` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `transaction_dates_ibfk_2`
    FOREIGN KEY (`transaction`)
    REFERENCES `tcslavens`.`transactions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 83
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tcslavens`.`transaction_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcslavens`.`transaction_items` (
  `id` INT(15) NOT NULL AUTO_INCREMENT,
  `transaction_id` INT(15) NOT NULL,
  `item_id` INT(15) NOT NULL,
  `queue` INT(15) NOT NULL,
  `notes` VARCHAR(100) NOT NULL,
  `type` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `status` (`queue` ASC),
  INDEX `transaction_id` (`transaction_id` ASC),
  INDEX `item_id` (`item_id` ASC),
  INDEX `q` (`queue` ASC),
  INDEX `type` (`type` ASC),
  INDEX `type_2` (`type` ASC),
  INDEX `type_3` (`type` ASC),
  CONSTRAINT `transaction_items_ibfk_1`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `tcslavens`.`transactions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `transaction_items_ibfk_2`
    FOREIGN KEY (`item_id`)
    REFERENCES `tcslavens`.`items` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `transaction_items_ibfk_3`
    FOREIGN KEY (`queue`)
    REFERENCES `tcslavens`.`queues` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `transaction_items_ibfk_4`
    FOREIGN KEY (`type`)
    REFERENCES `tcslavens`.`item_types` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 108
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tcslavens`.`transaction_parties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcslavens`.`transaction_parties` (
  `id` INT(15) NOT NULL AUTO_INCREMENT,
  `transaction_id` INT(15) NOT NULL,
  `contact_id` INT(15) NOT NULL,
  `party` INT(15) NOT NULL,
  `is_primary` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `contact_id` (`contact_id` ASC),
  INDEX `transaction_id` (`transaction_id` ASC),
  INDEX `role` (`party` ASC),
  CONSTRAINT `transaction_parties_ibfk_1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `tcslavens`.`contacts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `transaction_parties_ibfk_2`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `tcslavens`.`transactions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `transaction_parties_ibfk_3`
    FOREIGN KEY (`party`)
    REFERENCES `tcslavens`.`parties` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tcslavens`.`transaction_item_parties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcslavens`.`transaction_item_parties` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `transaction_item_id` INT(15) NOT NULL,
  `transaction_party_id` INT(15) NOT NULL,
  `complete` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `transaction_item_id` (`transaction_item_id` ASC, `transaction_party_id` ASC),
  INDEX `transaction_party_id` (`transaction_party_id` ASC),
  INDEX `transaction_party_id_2` (`transaction_party_id` ASC),
  CONSTRAINT `transaction_item_parties_ibfk_1`
    FOREIGN KEY (`transaction_item_id`)
    REFERENCES `tcslavens`.`transaction_items` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `transaction_item_parties_ibfk_2`
    FOREIGN KEY (`transaction_party_id`)
    REFERENCES `tcslavens`.`transaction_parties` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
